name: "Quill Git Semantic Version"
description: "Determines version of a repo based on git history"
branding:
  icon: "layers"
  color: "blue"
inputs:
  branch:
    description: "The branch name"
    required: true
    default: "master"
  tag_prefix:
    description: "The prefix to use to identify tags"
    required: false
    default: "v"
  major_pattern:
    description: "A string which, if present in a git commit, indicates that a change represents a major (breaking) change"
    required: true
    default: "(MAJOR)"
  minor_pattern:
    description: "A string which, if present in a git commit, indicates that a change represents a minor (feature) change"
    required: true
    default: "(MINOR)"
  format:
    description: "Pattern to use when formatting output version"
    required: true
    default: "${major}.${minor}.${patch}"
  change_path:
    description: "Path to check for changes. If any changes are detected in the path the 'changed' output will true. Enter multiple paths separated by spaces."
    required: false
  namespace:
    description: "Use to create a named sub-version. This value will be appended to tags created for this version."
    required: false
outputs:
  major:
    description: "Current major number"
  minor:
    description: "Current minor number"
  patch:
    description: "Current patch number"
  increment:
    description: "An additional value indicating the number of commits for the current version"
  version:
    description: "The version result, in the format {major}.{minor}.{patch}"
  version_tag:
    description: "The version result with trailing zeros removed"
  changed:
    description: "Indicates whether there was a change since the last version if change_path was specified. If no change_path was specified this value will always be true since the entire repo is considered."
runs:
  using: "node12"
  main: "dist/index.js"
